name: Regenerate Python Library
on:
  workflow_dispatch:
    inputs:
      library_version:
        description: 'The version of the new library'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Delete folder
        run: |
          rm -rf meraki
      - name: Regenerate Python Library
        run: |
          poetry run python generator/generate_library.py -g true -v ${{ github.event.inputs.library_version }} -o ${{ secrets.TEST_ORG_ID }} -k ${{ secrets.TEST_ORG_API_KEY }}
      - name: Set new version for Poetry
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ github.event.inputs.library_version }}\"/" pyproject.toml
      - name: Commit changes to new branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: support@meraki.com
          message: Automatically regenerated library to version ${{ github.event.inputs.library_version }}.
          new_branch: release
